#NOTE from Sep:
#This file is where we customize how the application runs. We will be adding more configurations here in the future,
#including database username, password, init script, twitch client key, secret, etc.

spring:
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG #Incoming HTTP requests
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE # Outgoing http requests

twitch:
  client-id: "c0ve1irt55xne1mjrcj5p0mpv4vtwq"
  secret: "g1di67qmz66zt1hgs3f0jgkevbvmcn"